import type { VehicleProblem, VehicleTemplate } from '../types/game'

export const VEHICLE_CATALOG: VehicleTemplate[] = [
  {
    id: 'clio-v',
    maker: 'Renault',
    model: 'Clio V',
    segment: 'Citadine',
    marketValue: 13_400,
    yearMin: 2019,
    yearMax: 2022,
    mileageMin: 38_000,
    mileageMax: 104_000,
  },
  {
    id: 'golf-vii',
    maker: 'Volkswagen',
    model: 'Golf VII',
    segment: 'Compacte',
    marketValue: 15_800,
    yearMin: 2017,
    yearMax: 2020,
    mileageMin: 56_000,
    mileageMax: 132_000,
  },
  {
    id: '208-ii',
    maker: 'Peugeot',
    model: '208 II',
    segment: 'Citadine',
    marketValue: 14_600,
    yearMin: 2020,
    yearMax: 2023,
    mileageMin: 27_000,
    mileageMax: 92_000,
  },
  {
    id: 'mini-f56',
    maker: 'Mini',
    model: 'Cooper F56',
    segment: 'Citadine premium',
    marketValue: 17_900,
    yearMin: 2016,
    yearMax: 2020,
    mileageMin: 49_000,
    mileageMax: 118_000,
  },
  {
    id: 'a3-8v',
    maker: 'Audi',
    model: 'A3 8V',
    segment: 'Compacte premium',
    marketValue: 19_500,
    yearMin: 2016,
    yearMax: 2019,
    mileageMin: 68_000,
    mileageMax: 139_000,
  },
  {
    id: 'c3-iii',
    maker: 'Citroën',
    model: 'C3 III',
    segment: 'Citadine',
    marketValue: 11_200,
    yearMin: 2018,
    yearMax: 2022,
    mileageMin: 44_000,
    mileageMax: 109_000,
  },
  {
    id: 'captur-i',
    maker: 'Renault',
    model: 'Captur I',
    segment: 'SUV urbain',
    marketValue: 13_900,
    yearMin: 2017,
    yearMax: 2020,
    mileageMin: 58_000,
    mileageMax: 127_000,
  },
  {
    id: 'fiesta-vii',
    maker: 'Ford',
    model: 'Fiesta VII',
    segment: 'Citadine',
    marketValue: 10_900,
    yearMin: 2018,
    yearMax: 2021,
    mileageMin: 47_000,
    mileageMax: 116_000,
  },
  {
    id: 'yaris-iv',
    maker: 'Toyota',
    model: 'Yaris IV',
    segment: 'Hybride',
    marketValue: 17_300,
    yearMin: 2020,
    yearMax: 2023,
    mileageMin: 31_000,
    mileageMax: 88_000,
  },
  {
    id: 'serie-1-f20',
    maker: 'BMW',
    model: 'Série 1 F20',
    segment: 'Compacte premium',
    marketValue: 18_800,
    yearMin: 2016,
    yearMax: 2019,
    mileageMin: 71_000,
    mileageMax: 143_000,
  },
  {
    id: 'duster-ii',
    maker: 'Dacia',
    model: 'Duster II',
    segment: 'SUV',
    marketValue: 15_200,
    yearMin: 2018,
    yearMax: 2021,
    mileageMin: 52_000,
    mileageMax: 124_000,
  },
  {
    id: 'mx5-nd',
    maker: 'Mazda',
    model: 'MX-5 ND',
    segment: 'Roadster',
    marketValue: 21_500,
    yearMin: 2016,
    yearMax: 2019,
    mileageMin: 42_000,
    mileageMax: 96_000,
  },
]

export const PROBLEM_CATALOG: Omit<VehicleProblem, 'repaired' | 'selectedForRepair'>[] = [
  {
    id: 'brakes',
    label: 'Freinage usé',
    detail: 'Disques et plaquettes avant',
    severity: 'critical',
    cost: 380,
    durationSeconds: 5,
    resaleImpact: 720,
  },
  {
    id: 'tires',
    label: 'Pneus à remplacer',
    detail: 'Train de pneus en fin de vie',
    severity: 'critical',
    cost: 460,
    durationSeconds: 6,
    resaleImpact: 780,
  },
  {
    id: 'timing',
    label: 'Distribution à prévoir',
    detail: 'Échéance constructeur dépassée',
    severity: 'critical',
    cost: 920,
    durationSeconds: 10,
    resaleImpact: 1_450,
  },
  {
    id: 'battery',
    label: 'Batterie faible',
    detail: 'Démarrage irrégulier à froid',
    severity: 'minor',
    cost: 190,
    durationSeconds: 3,
    resaleImpact: 390,
  },
  {
    id: 'bodywork',
    label: 'Carrosserie marquée',
    detail: 'Deux éléments à reprendre',
    severity: 'minor',
    cost: 680,
    durationSeconds: 8,
    resaleImpact: 1_080,
  },
  {
    id: 'service',
    label: 'Entretien en retard',
    detail: 'Vidange, filtres et contrôles',
    severity: 'minor',
    cost: 240,
    durationSeconds: 4,
    resaleImpact: 510,
  },
]
